#ifndef __CONFIG_H__

#define KERMITE_PROJECT_ID "GCX88nns"
#define KM0_ATMEGA_SINGLEWIRE__PIN_SIGNAL_PD2
#define KM0_ATMEGA_NEOPIXELCORE__PIN_RGBLED D3

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 48
#define KM0_RGB_LIGHTING__NUM_LEDS 27

#define KM0_OLED__ORIENTATION_HORIZONTALVIEW_ROT180

#define KS_NUM_COLUMNS 6
#define KS_NUM_ROWS 4

#define KS_COLUMN_PINS \
  { B3, B1, F7, F6, F5, F4 }

#define KS_ROW_PINS \
  { D4, C6, D7, E6 }

#endif