#ifndef __CONFIG_H__

#define KERMITE_PROJECT_ID "GCX88nns"
#define KM0_ATMEGA_SINGLEWIRE__PIN_SIGNAL_PD2
#define KM0_ATMEGA_NEOPIXELCORE__PIN_RGBLED P_D3

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 48
#define KM0_RGB_LIGHTING__NUM_LEDS 27

#define KM0_OLED__ORIENTATION_HORIZONTALVIEW_ROT180

#endif