#pragma once

#define KERMITE_FIRMWARE_ID "ZnVSZM"
#define KERMITE_KEYBOARD_NAME "dw4s"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 8

#define KM0_RP_SINGLEWIRE__PIN_SIGNAL GP1

#define KS_RGBLED_PIN GP28
#define KS_NUM_RGBLEDS 15

#define KS_NUM_DIRECT_WIRED_KEYS 4

#define KS_DIRECT_WIRED_KEY_INPUT_PINS \
  { GP13, GP14, GP15, GP16 }
