TARGET_MCU = rp2040
TARGET_STENCIL = stencil_default

KL_USE_SPLIT_KEYBOARD = 1
KL_USE_BOARD_LEDS_RPI_PICO = 1
KL_USE_DEBUG_UART = 1
KL_USE_OLED_DISPLAY = 1
KL_USE_RGB_LIGHTING = 1
KL_USE_KEYS_DIRECT_WIRED = 1
