#ifndef __CONFIG_H__

#define KERMITE_PROJECT_ID "RcYEeqNX"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 6
#define KM0_KEYBOARD__NUM_KEY_SLOTS 6

#define KM0_ENCODER_SCANNER__USE_SIMPLE_CAPTURE_METHOD

#endif