#pragma once

#define KERMITE_FIRMWARE_ID "7zabZ0"
#define KERMITE_KEYBOARD_NAME "SP2104"

#define KS_NUM_SCAN_SLOTS 56

#define KS_RP_SINGLEWIRE_PIN GP1

#define KS_NUM_COLUMNS 7
#define KS_NUM_ROWS 4

#define KS_COLUMN_PINS \
  { GP28, GP27, GP26, GP22, GP20, GP23, GP21 }

#define KS_ROW_PINS \
  { GP6, GP7, GP8, GP9 }
