#pragma once

#define KERMITE_FIRMWARE_ID "RcYEe2"

#define KS_NUM_SCAN_SLOTS 4

#define KS_NUM_DIRECT_WIRED_KEYS 4

#define KS_DIRECT_WIRED_KEY_INPUT_PINS \
  { GP12, GP13, GP14, GP15 }

#define KS_MOUSE_SENSOR_PIN_SCLK GP4
#define KS_MOUSE_SENSOR_PIN_SDIO GP5
#define KS_MOUSE_SENSOR_SWAP_XY
