#pragma once

#define KERMITE_PROJECT_ID "LN9M6TPO"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 4

#define KM0_ATMEGA_NEOPIXELCORE__PIN_RGBLED P_F4

#define KM0_RGB_LIGHTING__NUM_LEDS 15

#define KS_NUM_DIRECT_WIRED_KEYS 4

#define KS_DIRECT_WIRED_KEY_INPUT_PINS \
  { P_D7, P_E6, P_B4, P_B5 }
