#pragma once

#define KERMITE_FIRMWARE_ID "LN9M6T"
#define KERMITE_KEYBOARD_NAME "flash4"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 4

#define KS_NUM_RGBLEDS 15
#define KS_RGBLED_PIN P_F4

#define KS_NUM_DIRECT_WIRED_KEYS 4

#define KS_DIRECT_WIRED_KEY_INPUT_PINS \
  { P_D7, P_E6, P_B4, P_B5 }
