#pragma once

#define KERMITE_FIRMWARE_ID "Dc2M0J"
#define KERMITE_KEYBOARD_NAME "encoder_rp_split"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 6
#define KM0_RP_SINGLEWIRE__PIN_SIGNAL 1
#define KM0_RP_SINGLEWIRE__PIN_DEBUG_TIMING_MONITOR 2
