#ifndef __CONFIG_H__

#define KERMITE_PROJECT_ID "mVjx4qkV"

#define KM0_ATMEGA_SINGLEWIRE__PIN_SIGNAL_PD2
#define KM0_ATMEGA_NEOPIXELCORE__PIN_RGBLED P_B5
#define KM0_RGB_LIGHTING__NUM_LEDS 21

#define KM0_SPLIT_KEYBOARD__DEBUG_MASTER_SLAVE_DETEMINATION_PIN P_B2

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 42

#endif