import { VirtualKey } from './HighLevelDefs';
import { HID } from 'node-hid';

//HIDのキーコード定義, キーボードの言語やレイアウトによらない共通部分
const enum HidKey {
  KU_RESERVED = 0,
  KU_A = 4,
  KU_B,
  KU_C,
  KU_D,
  KU_E,
  KU_F,
  KU_G,
  KU_H,
  KU_I,
  KU_J,
  KU_K,
  KU_L,
  KU_M,
  KU_N,
  KU_O,
  KU_P,
  KU_Q,
  KU_R,
  KU_S,
  KU_T,
  KU_U,
  KU_V,
  KU_W,
  KU_X,
  KU_Y,
  KU_Z,

  KU_Num1 = 30,
  KU_Num2,
  KU_Num3,
  KU_Num4,
  KU_Num5,
  KU_Num6,
  KU_Num7,
  KU_Num8,
  KU_Num9,
  KU_Num0,

  KU_Enter = 40,
  KU_Escape,
  KU_BackSpace,
  KU_Tab,
  KU_Space,

  KU_CapsLock = 57,

  KU_F1 = 58,
  KU_F2,
  KU_F3,
  KU_F4,
  KU_F5,
  KU_F6,
  KU_F7,
  KU_F8,
  KU_F9,
  KU_F10,
  KU_F11,
  KU_F12,

  KU_PrintScreen = 70,
  KU_ScrollLock = 71,
  KU_Pause = 72,
  KU_Insert = 73,
  KU_Home = 74,
  KU_PageUp = 75,
  KU_Delete = 76,
  KU_End = 77,
  KU_PageDown = 78,
  KU_RightArrow = 79,
  KU_LeftArrow,
  KU_DownArrow,
  KU_UpArrow,
  KU_NumLock = 83,

  KU_F13 = 104,
  KU_F14,
  KU_F15,
  KU_F16,
  KU_F17,
  KU_F18,
  KU_F19,
  KU_F20,
  KU_F21,
  KU_F22,
  KU_F23,
  KU_F24,

  KU_Menu = 118,

  KU_LCtrl = 224,
  KU_LShift,
  KU_LAlt,
  KU_LGui,
  KU_RCtrl,
  KU_RShift,
  KU_RAlt,
  KU_RGui,

  KU_Ctrl = 224,
  KU_Shift,
  KU_Alt,
  KU_Gui
}

//日本語キーボード向けの定義
const enum HidKeyJp {
  KU__JP_Num1_Exclamation = 30,
  KU__JP_Num2_DoubleQuote,
  KU__JP_Num3_Sharp,
  KU__JP_Num4_Dollars,
  KU__JP_Num5_Percent,
  KU__JP_Num6_Ampersand,
  KU__JP_Num7_SingleQuote,
  KU__JP_Num8_LeftParenthesis,
  KU__JP_Num9_RightParenesis,

  KU__JP_Minus_Equal = 45,
  KU__JP_Circumflex_Tilde,
  KU__JP_Atmark_BackQuote,

  KU__JP_LeftSquareBracket_LeftCurlyBrace = 48,
  KU__JP_RightSquareBracket_RightCurlyBrace = 49,
  KU__JP_Semicolon_Plus = 51,
  KU__JP_Colon_Asterisk = 52,

  KU_HankakuZenkaku = 53,

  KU__JP_Comma_LessThan = 54,
  KU__JP_Dot_GreaterThan = 55,
  KU__JP_Slash_Question = 56,

  KU__JP_BackSlash_Underscore = 135,
  KU_KatakanaHiragana = 136,
  KU__JP_Yen_VertiacalBar = 137,
  KU_Henkan = 138,
  KU_Muhenkan = 139
}

const OUT_SHIFT = 0x100;
const OUT_NOSHIFT = 0x200;

export const HidKeyCodes: {
  [vk in VirtualKey]: number;
} = ({
  K_A: HidKey.KU_A,
  K_B: HidKey.KU_B,
  K_C: HidKey.KU_C,
  K_D: HidKey.KU_D,
  K_E: HidKey.KU_E,
  K_F: HidKey.KU_F,
  K_G: HidKey.KU_G,
  K_H: HidKey.KU_H,
  K_I: HidKey.KU_I,
  K_J: HidKey.KU_J,
  K_K: HidKey.KU_K,
  K_L: HidKey.KU_L,
  K_M: HidKey.KU_M,
  K_N: HidKey.KU_N,
  K_O: HidKey.KU_O,
  K_P: HidKey.KU_P,
  K_Q: HidKey.KU_Q,
  K_R: HidKey.KU_R,
  K_S: HidKey.KU_S,
  K_T: HidKey.KU_T,
  K_U: HidKey.KU_U,
  K_V: HidKey.KU_V,
  K_W: HidKey.KU_W,
  K_X: HidKey.KU_X,
  K_Y: HidKey.KU_Y,
  K_Z: HidKey.KU_Z,
  K_Num_0: HidKey.KU_Num0 | OUT_NOSHIFT,
  K_Num_1: HidKey.KU_Num1 | OUT_NOSHIFT,
  K_Num_2: HidKey.KU_Num2 | OUT_NOSHIFT,
  K_Num_3: HidKey.KU_Num3 | OUT_NOSHIFT,
  K_Num_4: HidKey.KU_Num4 | OUT_NOSHIFT,
  K_Num_5: HidKey.KU_Num5 | OUT_NOSHIFT,
  K_Num_6: HidKey.KU_Num6 | OUT_NOSHIFT,
  K_Num_7: HidKey.KU_Num7 | OUT_NOSHIFT,
  K_Num_8: HidKey.KU_Num8 | OUT_NOSHIFT,
  K_Num_9: HidKey.KU_Num9 | OUT_NOSHIFT,
  K_Escape: HidKey.KU_Escape,
  K_Space: HidKey.KU_Space,
  K_Enter: HidKey.KU_Enter,
  K_Tab: HidKey.KU_Tab,
  K_BackSpace: HidKey.KU_BackSpace,

  K_Dot: HidKeyJp.KU__JP_Dot_GreaterThan | OUT_NOSHIFT,
  K_Comma: HidKeyJp.KU__JP_Comma_LessThan | OUT_NOSHIFT,
  K_Exclamation: HidKeyJp.KU__JP_Num1_Exclamation | OUT_SHIFT,
  K_Question: HidKeyJp.KU__JP_Slash_Question | OUT_SHIFT,
  K_Colon: HidKeyJp.KU__JP_Colon_Asterisk | OUT_NOSHIFT,
  K_Semicolon: HidKeyJp.KU__JP_Semicolon_Plus | OUT_NOSHIFT,
  K_Underscore: HidKeyJp.KU__JP_BackSlash_Underscore | OUT_SHIFT,
  K_Plus: HidKeyJp.KU__JP_Semicolon_Plus | OUT_SHIFT,
  K_Minus: HidKeyJp.KU__JP_Minus_Equal | OUT_NOSHIFT,
  K_Asterisk: HidKeyJp.KU__JP_Colon_Asterisk | OUT_SHIFT,
  K_Slash: HidKeyJp.KU__JP_Slash_Question | OUT_NOSHIFT,
  K_Equal: HidKeyJp.KU__JP_Minus_Equal | OUT_SHIFT,
  K_Ampersand: HidKeyJp.KU__JP_Num6_Ampersand | OUT_SHIFT,
  K_VerticalBar: HidKeyJp.KU__JP_Yen_VertiacalBar | OUT_SHIFT,
  K_Hat: HidKeyJp.KU__JP_Circumflex_Tilde | OUT_NOSHIFT,
  K_Tilde: HidKeyJp.KU__JP_Circumflex_Tilde | OUT_SHIFT,
  K_AtMark: HidKeyJp.KU__JP_Atmark_BackQuote | OUT_NOSHIFT,
  K_Sharp: HidKeyJp.KU__JP_Num3_Sharp | OUT_SHIFT,
  K_Dollar: HidKeyJp.KU__JP_Num4_Dollars | OUT_SHIFT,
  K_Yen: HidKeyJp.KU__JP_Yen_VertiacalBar | OUT_NOSHIFT,
  K_Percent: HidKeyJp.KU__JP_Num5_Percent | OUT_SHIFT,
  K_BackSlash: HidKeyJp.KU__JP_BackSlash_Underscore | OUT_NOSHIFT,
  K_SingleQuote: HidKeyJp.KU__JP_Num7_SingleQuote | OUT_SHIFT,
  K_DoubleQuote: HidKeyJp.KU__JP_Num2_DoubleQuote | OUT_SHIFT,
  K_BackQuote: HidKeyJp.KU__JP_Atmark_BackQuote | OUT_SHIFT,
  K_LeftParenthesis: HidKeyJp.KU__JP_Num8_LeftParenthesis | OUT_SHIFT,
  K_RightParenthesis: HidKeyJp.KU__JP_Num9_RightParenesis | OUT_SHIFT,
  K_LeftSquareBracket:
    HidKeyJp.KU__JP_LeftSquareBracket_LeftCurlyBrace | OUT_NOSHIFT,
  K_RightSquareBracket:
    HidKeyJp.KU__JP_RightSquareBracket_RightCurlyBrace | OUT_NOSHIFT,
  K_LeftCurlyBrace:
    HidKeyJp.KU__JP_LeftSquareBracket_LeftCurlyBrace | OUT_SHIFT,
  K_RightCurlyBrace:
    HidKeyJp.KU__JP_RightSquareBracket_RightCurlyBrace | OUT_SHIFT,
  K_LessThan: HidKeyJp.KU__JP_Comma_LessThan | OUT_SHIFT,
  K_GreaterThan: HidKeyJp.KU__JP_Dot_GreaterThan | OUT_SHIFT,
  K_Shift: HidKey.KU_Shift,
  K_Ctrl: HidKey.KU_Ctrl,
  K_Alt: HidKey.KU_Alt,
  K_OS: HidKey.KU_Gui,
  K_LShift: HidKey.KU_LShift,
  K_LCtrl: HidKey.KU_LCtrl,
  K_LAlt: HidKey.KU_LAlt,
  K_LOS: HidKey.KU_LGui,
  K_RShift: HidKey.KU_RShift,
  K_RCtrl: HidKey.KU_RCtrl,
  K_RAlt: HidKey.KU_RAlt,
  K_ROS: HidKey.KU_RGui,
  K_Home: HidKey.KU_Home,
  K_End: HidKey.KU_End,
  K_Insert: HidKey.KU_Insert,
  K_Delete: HidKey.KU_Delete,
  K_PageUp: HidKey.KU_PageUp,
  K_PageDown: HidKey.KU_PageDown,
  K_LeftArrow: HidKey.KU_LeftArrow,
  K_RightArrow: HidKey.KU_RightArrow,
  K_UpArrow: HidKey.KU_UpArrow,
  K_DownArrow: HidKey.KU_DownArrow,
  K_HankakuZenkaku: HidKeyJp.KU_HankakuZenkaku,
  K_KatakanaHiragana: HidKeyJp.KU_KatakanaHiragana,
  K_Henkan: HidKeyJp.KU_Henkan,
  K_Muhenkan: HidKeyJp.KU_Muhenkan
  //todo: define all mapping entries
} as {
  [vk in VirtualKey]?: number;
}) as any;
// export type HidKeyCodes = typeof HidKeyCodes;
