#ifndef __HID_KEY_USAGE_H__
#define __HID_KEY_USAGE_H__

//HIDのキーコード定義, キーボードの言語やレイアウトによらない共通部分
enum {
  KU_RESERVED = 0,
  KU_A = 4,
  KU_B,
  KU_C,
  KU_D,
  KU_E,
  KU_F,
  KU_G,
  KU_H,
  KU_I,
  KU_J,
  KU_K,
  KU_L,
  KU_M,
  KU_N,
  KU_O,
  KU_P,
  KU_Q,
  KU_R,
  KU_S,
  KU_T,
  KU_U,
  KU_V,
  KU_W,
  KU_X,
  KU_Y,
  KU_Z,

  KU_Num1 = 30,
  KU_Num2,
  KU_Num3,
  KU_Num4,
  KU_Num5,
  KU_Num6,
  KU_Num7,
  KU_Num8,
  KU_Num9,
  KU_Num0,

  KU_Enter = 40,
  KU_Escape,
  KU_BackSpace,
  KU_Tab,
  KU_Space,

  KU_CapsLock = 57,

  KU_F1 = 58,
  KU_F2,
  KU_F3,
  KU_F4,
  KU_F5,
  KU_F6,
  KU_F7,
  KU_F8,
  KU_F9,
  KU_F10,
  KU_F11,
  KU_F12,

  KU_PrintScreen = 70,
  KU_ScrollLock = 71,
  KU_Pause = 72,
  KU_Insert = 73,
  KU_Home = 74,
  KU_PageUp = 75,
  KU_Delete = 76,
  KU_End = 77,
  KU_PageDown = 78,
  KU_RightArrow = 79,
  KU_LeftArrow,
  KU_DownArrow,
  KU_UpArrow,
  KU_NumLock = 83,

  KU_F13 = 104,
  KU_F14,
  KU_F15,
  KU_F16,
  KU_F17,
  KU_F18,
  KU_F19,
  KU_F20,
  KU_F21,
  KU_F22,
  KU_F23,
  KU_F24,

  KU_Menu = 118,

  KU__Modifers = 0x100,
  KU_Ctrl = 0x100,
  KU_Shift = 0x200,
  KU_Alt = 0x400,
  KU_OS = 0x800,
};

//日本語キーボード向けの定義
enum {
  KU__JP_Num1_Exclamation = 30,
  KU__JP_Num2_DoubleQuote,
  KU__JP_Num3_Sharp,
  KU__JP_Num4_Dollars,
  KU__JP_Num5_Percent,
  KU__JP_Num6_Ampersand,
  KU__JP_Num7_SingleQuote,
  KU__JP_Num8_LeftParenthesis,
  KU__JP_Num9_RightParenesis,

  KU__JP_Minus_Equal = 45,
  KU__JP_Circumflex_Tilde,
  KU__JP_Atmark_BackQuote,

  KU__JP_LeftSquareBracket_LeftCurlyBrace = 48,
  KU__JP_RightSquareBracket_RightCurlyBrace = 49,
  KU__JP_Semicolon_Plus = 51,
  KU__JP_Colon_Asterisk = 52,

  KU_HankakuZenkaku = 53,

  KU__JP_Comma_LessThan = 54,
  KU__JP_Dot_GreaterThan = 55,
  KU__JP_Slash_Question = 56,

  KU__JP_BackSlash_Underscore = 135,
  KU_KatakanaHiragana = 136,
  KU__JP_Yen_VertiacalBar = 137,
  KU_Henkan = 138,
  KU_Muhenkan = 139,
};

#endif