#ifndef __LOCALIZATION_KEY_MAPPING_TABLE_JP_H__
#define __LOCALIZATION_KEY_MAPPING_TABLE_JP_H__

#include "types.h"
#include <avr/pgmspace.h>

#include "HidKeyUsages.h"

const uint16_t LogicalKeyToHidKeyTable_JP[] PROGMEM = {
  KU_RESERVED,
  KU_A,
  KU_B,
  KU_C,
  KU_D,
  KU_E,
  KU_F,
  KU_G,
  KU_H,
  KU_I,
  KU_J,
  KU_K,
  KU_L,
  KU_M,
  KU_N,
  KU_O,
  KU_P,
  KU_Q,
  KU_R,
  KU_S,
  KU_T,
  KU_U,
  KU_V,
  KU_W,
  KU_X,
  KU_Y,
  KU_Z,

  KU_Num0,
  KU_Num1,
  KU_Num2,
  KU_Num3,
  KU_Num4,
  KU_Num5,
  KU_Num6,
  KU_Num7,
  KU_Num8,
  KU_Num9,

  KU_Escape,
  KU_Space,
  KU_Enter,
  KU_Tab,
  KU_BackSpace,

  KU_F1,
  KU_F2,
  KU_F3,
  KU_F4,
  KU_F5,
  KU_F6,
  KU_F7,
  KU_F8,
  KU_F9,
  KU_F10,
  KU_F11,
  KU_F12,

  KU__JP_Dot_GreaterThan,
  KU__JP_Comma_LessThan,
  KU__JP_Num1_Exclamation | KU_Shift,
  KU__JP_Slash_Question | KU_Shift,
  KU__JP_Colon_Asterisk,
  KU__JP_Semicolon_Plus,
  KU__JP_BackSlash_Underscore | KU_Shift,
  KU__JP_Semicolon_Plus | KU_Shift,
  KU__JP_Minus_Equal,
  KU__JP_Colon_Asterisk | KU_Shift,
  KU__JP_Slash_Question,
  KU__JP_Minus_Equal | KU_Shift,
  KU__JP_Num6_Ampersand | KU_Shift,
  KU__JP_Yen_VertiacalBar | KU_Shift,
  KU__JP_Circumflex_Tilde,
  KU__JP_Circumflex_Tilde | KU_Shift,
  KU__JP_Atmark_BackQuote,
  KU__JP_Num3_Sharp | KU_Shift,
  KU__JP_Num4_Dollars | KU_Shift,
  KU__JP_Yen_VertiacalBar,
  KU__JP_Num5_Percent | KU_Shift,
  KU__JP_BackSlash_Underscore,
  KU__JP_Num7_SingleQuote | KU_Shift,
  KU__JP_Num2_DoubleQuote | KU_Shift,
  KU__JP_Atmark_BackQuote | KU_Shift,
  KU__JP_Num8_LeftParenthesis | KU_Shift,
  KU__JP_Num9_RightParenesis | KU_Shift,
  KU__JP_LeftSquareBracket_LeftCurlyBrace,
  KU__JP_RightSquareBracket_RightCurlyBrace,
  KU__JP_LeftSquareBracket_LeftCurlyBrace | KU_Shift,
  KU__JP_RightSquareBracket_RightCurlyBrace | KU_Shift,
  KU__JP_Comma_LessThan | KU_Shift,
  KU__JP_Dot_GreaterThan | KU_Shift,

  KU_Shift,
  KU_Ctrl,
  KU_Alt,
  KU_OS,

  KU_Home,
  KU_End,
  KU_Insert,
  KU_Delete,
  KU_PageUp,
  KU_PageDown,

  KU_LeftArrow,
  KU_RightArrow,
  KU_UpArrow,
  KU_DownArrow,

  KU_PrintScreen,
  KU_CapsLock,
  KU_ScrollLock,
  KU_Pause,
  KU_Menu,

  KU_HankakuZenkaku,
  KU_KatakanaHiragana,
  KU_Muhenkan,
  KU_Henkan,

  //Specials
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,

  KU_F13,
  KU_F14,
  KU_F15,
  KU_F16,
  KU_F17,
  KU_F18,
  KU_F19,
  KU_F20,
  KU_F21,
  KU_F22,
  KU_F23,
  KU_F24,

};

#endif