#ifndef __CONFIG_H__

#define KERMITE_PROJECT_ID "LN9M6TPO"

#define KM0_KEYBOARD__NUM_KEY_SLOTS 4
#define KM0_KEYBOARD__NUM_SCAN_SLOTS 4

#define KM0_ATMEGA_NEOPIXELCORE__PIN_RGBLED P_F4

#define KM0_RGB_LIGHTING__NUM_LEDS 15

#endif