#pragma once

#define KERMITE_FIRMWARE_ID "RcYEe4"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 4

#define KM0_KEYBOARD_STATUS_LEDS__LED_PINS \
  { GP7, GP8, GP9 }

#define KM0_KEYBOARD_STATUS_LEDS__LED_DRIVE_MODE_SINK
