#pragma once

#define KERMITE_FIRMWARE_ID "000000"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 10

#define KM0_ATMEGA_SINGLEWIRE__PIN_SIGNAL P_D0

#define KM0_RGB_LIGHTING__NUM_LEDS 10

#define KM0_ATMEGA_NEOPIXELCORE__PIN_RGBLED P_F4

#define KS_NUM_COLUMNS 10
#define KS_NUM_ROWS 10

#define KS_COLUMN_PINS \
  {}

#define KS_ROW_PINS \
  {}

#define KM0_HALF_DUPLEX_SERIAL__PIN_SCLK GP4
#define KM0_HALF_DUPLEX_SERIAL__PIN_SDIO GP5