#pragma once

#define KERMITE_FIRMWARE_ID "HCV52K"
#define KERMITE_KEYBOARD_NAME "standard"

#define KM0_ENCODER_SCANNER__NUM_ENCODERS_MAX 3
#define KM0_ATMEGA_NEOPIXELCORE__PIN_RGBLED P_D3

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 128