import { IBoardPinAssignsData } from '~/ui/fabrics/controllerPinAssignsSection/types';

export const boardAssignsData_rpiPico: IBoardPinAssignsData = {
  unitPixels: 16,
  boardUnitWidth: 8,
  boardUnitHeight: 21,
  pinsRowOffset: 1,
  boardImageSig: 'rpiPico',
  pinNames: [
    'GP0',
    'GP1',
    'GND',
    'GP2',
    'GP3',
    'GP4',
    'GP5',
    'GND',
    'GP6',
    'GP7',
    'GP8',
    'GP9',
    'GND',
    'GP10',
    'GP11',
    'GP12',
    'GP13',
    'GND',
    'GP14',
    'GP15',
    'GP16',
    'GP17',
    'GND',
    'GP18',
    'GP19',
    'GP20',
    'GP21',
    'GND',
    'GP22',
    'RUN',
    'GP26',
    'GP27',
    'GND',
    'GP28',
    'AVREF',
    '3V3OUT',
    '3V3_EN',
    'GND',
    'VSYS',
    'VBUS',
  ],
};

export const boardAssignsData_proMicroRp2040: IBoardPinAssignsData = {
  unitPixels: 18,
  boardUnitWidth: 7,
  boardUnitHeight: 14,
  pinsRowOffset: 2,
  boardImageSig: 'proMicroRp2040',
  pinNames: [
    'GP0',
    'GP1',
    'GND',
    'GND',
    'GP2',
    'GP3',
    'GP4',
    'GP5',
    'GP6',
    'GP7',
    'GP8',
    'GP9',
    'GP21',
    'GP23',
    'GP20',
    'GP22',
    'GP26',
    'GP27',
    'GP28',
    'GP29',
    'VCC',
    '#RST',
    'GND',
    'RAW',
  ],
};

export const boardAssignsData_kb2040: IBoardPinAssignsData = {
  unitPixels: 18,
  boardUnitWidth: 7,
  boardUnitHeight: 14,
  pinsRowOffset: 1,
  boardImageSig: 'kb2040',
  pinNames: [
    'D+',
    'GP0',
    'GP1',
    'GND',
    'GND',
    'GP2',
    'GP3',
    'GP4',
    'GP5',
    'GP6',
    'GP7',
    'GP8',
    'GP9',
    'GP10',
    'GP19',
    'GP20',
    'GP18',
    'GP26',
    'GP27',
    'GP28',
    'GP29',
    'VCC',
    '#RST',
    'GND',
    'RAW',
    'D-',
  ],
};

export const boardAssignsData_xiaoRp2040: IBoardPinAssignsData = {
  unitPixels: 18,
  boardUnitWidth: 7,
  boardUnitHeight: 10,
  pinsRowOffset: 2,
  boardImageSig: 'xiaoRp2040',
  pinNames: [
    'GP26',
    'GP27',
    'GP28',
    'GP29',
    'GP6',
    'GP7',
    'GP0',
    'GP1',
    'GP2',
    'GP4',
    'GP3',
    '3V3',
    'GND',
    '5V',
  ],
};

export const boardAssignsData_rp2040zero: IBoardPinAssignsData = {
  unitPixels: 18,
  boardUnitWidth: 7,
  boardUnitHeight: 11,
  pinsRowOffset: 1,
  boardImageSig: 'rp2040Zero',
  pinNames: [
    '5V',
    'GND',
    '3V3',
    'GP29',
    'GP28',
    'GP27',
    'GP26',
    'GP15',
    'GP14',
    //
    'GP8',
    'GP7',
    'GP6',
    'GP5',
    'GP4',
    'GP3',
    'GP2',
    'GP1',
    'GP0',
  ],
  pinNamesBottom: ['GP13', 'GP12', 'GP11', 'GP10', 'GP9'],
};
