#ifndef __VERSIONS_H__

#define CONFIG_STORAGE_FORMAT_REVISION 2

#define RAWHID_MESSAGE_PROTOCOL_REVISION 1

#ifndef PROJECT_RELEASE_BUILD_REVISION
#error PROJECT_RELEASE_BUILD_REVISION is not provided
#endif

#endif