#ifndef __CONFIG_H__

#define KERMITE_PROJECT_ID "2xUWcB80"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 14
#define KM0_KEYBOARD__NUM_KEY_SLOTS 14

#define KM0_RP_SERIAL_LED__PIN_LED GP29
#define KM0_RGB_LIGHTING__NUM_LEDS 12

#define KM0_ENCODER_SCANNER__USE_SIMPLE_CAPTURE_METHOD

#endif
