TARGET_MCU = rp2040
TARGET_STENCIL = stencil_general

KL_USE_BOARD_LEDS_PROMICRO_RP = 1
KL_USE_DEBUG_UART = 1
KL_USE_OLED_DISPLAY = 1
KL_USE_RGB_LIGHTING = 1
KL_USE_KEY_MATRIX = 1
KL_USE_ENCODERS = 1
