#pragma once

#define KERMITE_PROJECT_ID "ZnVSZMbi"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 8

#define KM0_ATMEGA_NEOPIXELCORE__PIN_RGBLED F4
#define KM0_RGB_LIGHTING__NUM_LEDS 15
#define KM0_ATMEGA_SINGLEWIRE__PIN_SIGNAL_PD2

#define KS_NUM_DW_KEYS 4

#define KS_DW_KEY_INPUT_PINS \
  { E6, B4, B5, B6 }
