#pragma once

#define KERMITE_PROJECT_ID "RcYEeq"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 4

#define KM0_HALF_DUPLEX_SERIAL__PIN_SCLK D4
#define KM0_HALF_DUPLEX_SERIAL__PIN_SDIO C6

#define KM0_OPTICAL_SENSOR__SWAP_XY
