#pragma once

#define KERMITE_PROJECT_ID "RcYEeq"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 4

#define KM0_KEYBOARD_STATUS_LEDS__LED_PINS \
  { D1, D0, D4 }

#define KM0_KEYBOARD_STATUS_LEDS__LED_DRIVE_MODE_SINK
