// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// neopixel_emitter //
// ---------------- //

#define neopixel_emitter_wrap_target 0
#define neopixel_emitter_wrap 10

static const uint16_t neopixel_emitter_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0xe037, //  1: set    x, 23                      
    0x6041, //  2: out    y, 1                       
    0x0067, //  3: jmp    !y, 7                      
    0xbc42, //  4: nop                    side 1 [4] 
    0xb042, //  5: nop                    side 0     
    0x0009, //  6: jmp    9                          
    0xb942, //  7: nop                    side 1 [1] 
    0xb142, //  8: nop                    side 0 [1] 
    0x0042, //  9: jmp    x--, 2                     
    0xa742, // 10: nop                           [7] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program neopixel_emitter_program = {
    .instructions = neopixel_emitter_program_instructions,
    .length = 11,
    .origin = -1,
};

static inline pio_sm_config neopixel_emitter_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + neopixel_emitter_wrap_target, offset + neopixel_emitter_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

