#pragma once

#define KERMITE_PROJECT_ID "RcYEeq"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 6
#define KM0_KEYBOARD__RIGHTHAND_SCAN_SLOTS_OFFSET 2
#define KM0_ATMEGA_SINGLEWIRE__PIN_SIGNAL D2

#define KS_NUM_DIRECT_WIRED_KEYS 2
#define KS_NUM_DIRECT_WIRED_KEYS_RIGHT 4
#define KS_DIRECT_WIRED_KEY_INPUT_PINS \
  { B5, B6 }
#define KS_DIRECT_WIRED_KEY_INPUT_PINS_RIGHT \
  { E6, B4, B5, B6 }
