#pragma once

#define KERMITE_FIRMWARE_ID "ZnVSZL"
#define KERMITE_KEYBOARD_NAME "dw4s"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 8

#define KM0_ATMEGA_SINGLEWIRE__PIN_SIGNAL D0

#define KS_NUM_DIRECT_WIRED_KEYS 4

#define KS_DIRECT_WIRED_KEY_INPUT_PINS
