import { IBoardPinAssignsData } from '~/ui/features/ProjectQuickSetupPart/sections/ControllerPinAssignsSection/types';

export const boardAssignsData_proMicro: IBoardPinAssignsData = {
  unitPixels: 18,
  boardUnitWidth: 7,
  boardUnitHeight: 14,
  pinsRowOffset: 2,
  boardImageSig: 'proMicro',
  pinNames: [
    'PD3',
    'PD2',
    'GND',
    'GND',
    'PD1',
    'PD0',
    'PD4',
    'PC6',
    'PD7',
    'PE6',
    'PB4',
    'PB5',
    'PB6',
    'PB2',
    'PB3',
    'PB1',
    'PF7',
    'PF6',
    'PF5',
    'PF4',
    'VCC',
    '#RST',
    'GND',
    'RAW',
  ],
};

export const boardAssignsData_proMicroRp2040: IBoardPinAssignsData = {
  unitPixels: 18,
  boardUnitWidth: 7,
  boardUnitHeight: 14,
  pinsRowOffset: 2,
  boardImageSig: 'proMicroRp2040',
  pinNames: [
    'GP0',
    'GP1',
    'GND',
    'GND',
    'GP2',
    'GP3',
    'GP4',
    'GP5',
    'GP6',
    'GP7',
    'GP8',
    'GP9',
    'GP21',
    'GP23',
    'GP20',
    'GP22',
    'GP26',
    'GP27',
    'GP28',
    'GP29',
    'VCC',
    '#RST',
    'GND',
    'RAW',
  ],
};

export const boardAssignsData_rpiPico: IBoardPinAssignsData = {
  unitPixels: 13,
  boardUnitWidth: 8,
  boardUnitHeight: 21,
  pinsRowOffset: 1,
  boardImageSig: 'rpiPico',
  pinNames: [
    'GP0',
    'GP1',
    'GND',
    'GP2',
    'GP3',
    'GP4',
    'GP5',
    'GND',
    'GP6',
    'GP7',
    'GP8',
    'GP9',
    'GND',
    'GP10',
    'GP11',
    'GP12',
    'GP13',
    'GND',
    'GP14',
    'GP15',
    'GP16',
    'GP17',
    'GND',
    'GP18',
    'GP19',
    'GP20',
    'GP21',
    'GND',
    'GP22',
    'RUN',
    'GP26',
    'GP27',
    'GND',
    'GP28',
    'AVREF',
    '3V3OUT',
    '3V3_EN',
    'GND',
    'VSYS',
    'VBUS',
  ],
};
