#pragma once

#define KERMITE_FIRMWARE_ID "HCV53A"
#define KERMITE_KEYBOARD_NAME "standard"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 128

#define KM0_ATMEGA_SINGLEWIRE__PIN_SIGNAL P_D2
#define KM0_ATMEGA_NEOPIXELCORE__PIN_RGBLED P_D3
