#pragma once

#define KERMITE_FIRMWARE_ID "RcYEe1"

#define KM0_HALF_DUPLEX_SERIAL__PIN_SCLK GP4
#define KM0_HALF_DUPLEX_SERIAL__PIN_SDIO GP5

#define KM0_OPTICAL_SENSOR__SWAP_XY

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 4
