#pragma once

#define KERMITE_PROJECT_ID "ZnVSZMbi"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 8

#define KM0_RP_SINGLEWIRE__PIN_SIGNAL GP1

#define KM0_RP_SERIAL_LED__PIN_LED GP28
#define KM0_RGB_LIGHTING__NUM_LEDS 15
#define KM0_RGB_LIGHTING__NUM_LEDS_RIGHT 8

#define KS_NUM_DIRECT_WIRED_KEYS 4

#define KS_DIRECT_WIRED_KEY_INPUT_PINS \
  { GP13, GP14, GP15, GP16 }
