#pragma once

#if defined(KERMITE_TARGET_MCU_RP2040)
#define __IS_RP2040
#else
#error KERMITE_TARGET_MCU_* is not defined
#endif

#ifdef KS_NUM_SCAN_SLOTS
#define KM0_KEYBOARD__NUM_SCAN_SLOTS KS_NUM_SCAN_SLOTS
#endif

#ifdef KS_RIGHTHAND_SCAN_SLOTS_OFFSET
#define KM0_KEYBOARD__RIGHTHAND_SCAN_SLOTS_OFFSET KS_RIGHTHAND_SCAN_SLOTS_OFFSET
#endif

#ifdef KS_USB_MANUFATURER
#define KM0_USB__MANUFACTURER_TEXT KS_USB_MANUFATURER
#endif

#ifdef KS_USB_PRODUCT
#define KM0_USB__PRODUCT_TEXT KS_USB_PRODUCT
#endif

#ifdef KS_SNGLEWIRE_PIN
#define KM0_ATMEGA_SINGLEWIRE__PIN_SIGNAL KS_SNGLEWIRE_PIN
#endif

#ifdef KS_RP_SINGLEWIRE_PIN
#define KM0_RP_SINGLEWIRE__PIN_SIGNAL KS_RP_SINGLEWIRE_PIN
#endif

#ifdef KS_OLED_ROT180
#define KM0_OLED__ORIENTATION_HORIZONTALVIEW_ROT180
#endif

#ifdef KS_MOUSE_SENSOR_PIN_SCLK
#define KM0_HALF_DUPLEX_SERIAL__PIN_SCLK KS_MOUSE_SENSOR_PIN_SCLK
#endif

#ifdef KS_MOUSE_SENSOR_PIN_SDIO
#define KM0_HALF_DUPLEX_SERIAL__PIN_SDIO KS_MOUSE_SENSOR_PIN_SDIO
#endif

#ifdef KS_MOUSE_SENSOR_SWAP_XY
#define KM0_OPTICAL_SENSOR__SWAP_XY KS_MOUSE_SENSOR_SWAP_XY
#endif

#ifdef KS_MOUSE_SENSOR_INVERT_X
#define KM0_OPTICAL_SENSOR__INVERT_X KS_MOUSE_SENSOR_INVERT_X
#endif

#ifdef KS_MOUSE_SENSOR_INVERT_Y
#define KM0_OPTICAL_SENSOR__INVERT_Y KS_MOUSE_SENSOR_INVERT_Y
#endif

#ifdef KS_KEYBOARD_STATUS_LEDS_PINS
#define KM0_KEYBOARD_STATUS_LEDS__LED_PINS KS_KEYBOARD_STATUS_LEDS_PINS
#endif

#ifdef KS_KEYBOARD_STATUS_LEDS_SINK
#define KM0_KEYBOARD_STATUS_LEDS__LED_DRIVE_MODE_SINK
#endif
