#pragma once

#if defined(KERMITE_TARGET_MCU_ATMEGA)
#define __IS_ATMEGA
#elif defined(KERMITE_TARGET_MCU_RP2040)
#define __IS_RP2040
#endif

#ifdef KS_NUM_SCAN_SLOTS
#define KM0_KEYBOARD__NUM_SCAN_SLOTS KS_NUM_SCAN_SLOTS
#endif

#ifdef KS_RIGHTHAND_SCAN_SLOTS_OFFSET
#define KM0_KEYBOARD__RIGHTHAND_SCAN_SLOTS_OFFSET KS_RIGHTHAND_SCAN_SLOTS_OFFSET
#endif

#ifdef KS_USB_MANUFATURER
#define KM0_USB__MANUFACTURER_TEXT KS_USB_MANUFATURER
#endif

#ifdef KS_USB_PRODUCT
#define KM0_USB__PRODUCT_TEXT KS_USB_PRODUCT
#endif

#ifdef KS_NUM_RGBLEDS
#define KM0_RGB_LIGHTING__NUM_LEDS KS_NUM_RGBLEDS
#endif

#ifdef KS_RGBLED_PIN
#ifdef __IS_ATMEGA
#define KM0_ATMEGA_NEOPIXELCORE__PIN_RGBLED KS_RGBLED_PIN
#endif
#ifdef __IS_RP2040
#define KM0_RP_SERIAL_LED__PIN_LED KS_RGBLED_PIN
#endif
#endif

#ifdef KS_SNGLEWIRE_PIN_PD0
#define KM0_ATMEGA_SINGLEWIRE__PIN_SIGNAL_PD0
#endif

#ifdef KS_SNGLEWIRE_PIN_PD2
#define KM0_ATMEGA_SINGLEWIRE__PIN_SIGNAL_PD2
#endif

#ifdef KS_RP_SINGLEWIRE_PIN
#define KM0_RP_SINGLEWIRE__PIN_SIGNAL KS_RP_SINGLEWIRE_PIN
#endif

#ifdef KS_OLED_ROT180
#define KM0_OLED__ORIENTATION_HORIZONTALVIEW_ROT180
#endif