#ifndef __EEPROM_LAYOUT_H__
#define __EEPROM_LAYOUT_H__


#define EEPROM_BASE_ADDR_PROJECT_ID 0
#define EEPROM_BASE_ADDR_CUSTOM_SETTINGS_BYTES_INITILIZATION_FLAG 9
#define EEPROM_BASE_ADDR_CUSTOM_SETTINGS_BYTES 10
#define EEPROM_BASE_ADDR_ASSIGN_STORAGE 20


#define ASSIGN_STORAGE_HEADER_LENGTH 12


#endif