// generated by Kermite/software/misc/ui_texts_code_generator.ts

// prettier-ignore
export const textSourceEnglish = {
  STUB: 'TODO: specify text for this element',
  hint_titleBar_switchToWidgetView: 'Switch to widget view',
  hint_titleBar_minimizeWindow: 'Minimize window',
  hint_titleBar_maximizeWindow: 'Maximize window',
  hint_titleBar_closeApplication: 'Close application',
  hint_globalMenuButton: 'Show global menu',
  label_globalMenu_showTestInputArea: 'Show test input area',
  label_globalMenu_theme_light: 'Light Theme',
  label_globalMenu_theme_dark: 'Dark Theme',
  label_globalMenu_language_english: 'English',
  label_globalMenu_language_japanese: 'Japanese',
  hint_globalMenu_showTestInputArea: 'Show text filed for key input test',
  hint_globalMenu_theme_light: 'Switch to light theme',
  hint_globalMenu_theme_dark: 'Switch to dark theme',
  hint_globalMenu_language_english: 'Show UI in English',
  hint_globalMenu_language_japanese: 'Show UI in Japanese',
  hint_assigner_topBar_profileOperationsMenu: 'Open profile operations menu',
  label_assigner_menu_newProfile: 'new',
  label_assigner_menu_saveProfile: 'save',
  label_assigner_menu_renameProfile: 'rename',
  label_assigner_menu_copyProfile: 'copy',
  label_assigner_menu_deleteProfile: 'delete',
  label_assigner_menu_importFromFile: 'import from file',
  label_assigner_menu_exportToFile: 'export to file',
  label_assigner_menu_saveAsPreset: 'save as preset',
  label_assigner_menu_openUserProfilesFolder: 'open user profiles folder',
  hint_assigner_menu_newProfile: 'Create new profile',
  hint_assigner_menu_saveProfile: 'Save profile',
  hint_assigner_menu_renameProfile: 'Rename profile',
  hint_assigner_menu_copyProfile: 'Duplicate profile',
  hint_assigner_menu_deleteProfile: 'Delete profile',
  hint_assigner_menu_importFromFile: '',
  hint_assigner_menu_exportToFile: '',
  hint_assigner_menu_saveAsPreset: 'Save profile as preset',
  hint_assigner_menu_openUserProfilesFolder:
    'Open user profiles folder in default file manager of OS.',
  label_assigner_topBar_saveAssignsButton: 'save',
  label_assigner_topBar_writeAssignsButton: 'write',
  hint_assigner_topBar_saveAssignsButton: 'Save edit profile',
  hint_assigner_topBar_writeAssignsButton:
    'Save edit profile and write keymapping to the device',
  hint_assigner_topBar_selectCurrentProfile: 'Select current profile',
  hint_assigner_topBar_profileConfigurationButton:
    'Open profile configuration modal',
  hint_assigner_topBar_keyboardBehaviorModeSelector:
    'Select keyboard behavior mode. (STD: Standalone Mode, SIM: Simulation Mode)',
  hint_assigner_topBar_keyboardSystemLayoutSelector:
    'Select keyboard layout recognized by OS',
  hint_assigner_topBar_routingChannelSelector: 'Select assign routing channel',
  hint_assigner_topBar_connectedKeyboardName: 'Connected keyboard name',
  hint_assigner_topBar_deviceConnectionStatus: 'Device connection status',
  label_assigner_testInputArea_clearButton: 'clear',
  hint_assigner_testInputArea_inputField: 'Test input area for typing.',
  hint_assigner_testInputArea_clearButton: 'Clear input text.',
  hint_assigner_keyboardView_layerStates:
    'Layer states: Affects current layter states of the device.',
  hint_assigner_keyboardView_keyUnit: 'Select edit target key',
  hint_assigner_assigns_pri:
    'Select primary assign slot. Primary assigns are fired when key down or tap.',
  hint_assigner_assigns_sec:
    'Select secondary assign slot. Secondary assigns are fired when key hold.',
  hint_assigner_assigns_ter:
    'Select tertiary assign slot. Tertiary assigns are fired when double tap detected.',
  hint_assigner_assigns_none: 'Clear assign',
  hint_assigner_assigns_transparent:
    'Set transparent assign. lookup flow skips the layer.',
  hint_assigner_assigns_block: 'Set block assign. lookup flow is stopped.',
  hint_assigner_assigns_keyInput: 'Set key input assigns.',
  hint_assigner_assigns_modifiers: 'Set modifiers attached to key input',
  hint_assigner_assigns_layers: 'Set layer assigns',
  hint_assigner_assigns_clearExclusiveGroup:
    'Clear all layers belongs to the same exclusion group',
  hint_assigner_assigns_layerInvocationModeSelector:
    'Select layer invocation mode',
  label_assigner_layerListHeader: 'Layers',
  hint_assigner_layers_layerListHeader: 'Layer List',
  hint_assigner_layers_layerListItems: 'Select edit target layer',
  hint_assigner_layerOps_addNewLayer: 'Add new layer',
  hint_assigner_layerOps_editLayerProperties: 'Edit layer properties',
  hint_assigner_layerOps_deleteLayer: 'Delete layer',
  hint_assigner_layerOps_bringBackward: 'Bring layer backward',
  hint_assigner_layerOps_bringForward: 'Bring layer forward',
  label_assigner_configs_assignModel: 'Logic Model',
  label_assigner_configs_showLayersDynamic: 'Show Layers Dynamic',
  label_assigner_configs_showFallbackAssigns: 'Show Fallback Assigns',
  hint_assigner_configs_assignModel: 'Logic model for current profile',
  hint_assigner_configs_showLayersDynamic:
    'Show layers synchronized to the connected keyboard device',
  hint_assigner_configs_showFallbackAssigns:
    'Show fallback assigns of the layer',
  label_assigner_profileConfigModal_modalTitle: 'profile configuration',
  label_assigner_profileConfigModal_assignModel: 'logic model',
  label_assigner_profileConfigModal_dualMode_header: 'dual mode settings',
  label_assigner_profileConfigModal_dualMode_primaryDefaultTrigger:
    'primary default trigger',
  label_assigner_profileConfigModal_dualMode_tapHoldThreshold:
    'tap hold threshold',
  label_assigner_profileConfigModal_dualMode_useInterruptHold:
    'use interrupt hold',
  label_assigner_profileConfigModal_shiftCancel: 'use shift cancel feature',
  hint_assigner_profileConfigModal_assignModel:
    'Select logic model. (single: single assign for each key, dual: multiple assigns for each key)',
  hint_assigner_profileConfigModal_dualMode_header:
    'Settings specific for logic model Dual.',
  hint_assigner_profileConfigModal_dualMode_primaryDefaultTrigger:
    'Set trigger action of primary assign when there is no assign for secondary slot. ',
  hint_assigner_profileConfigModal_dualMode_tapHoldThreshold:
    'Adjust the time threshold for top/hold detection.',
  hint_assigner_profileConfigModal_dualMode_useInterruptHold:
    'Regard first key as hold when subsequent keys pressed within the time.',
  hint_assigner_profileConfigModal_shiftCancel:
    'Temporary disable shifts for non-shifted symbol inputs.',
  label_assigner_layerModal_modalTitleAdd: 'Add Layer',
  label_assigner_layerModal_modalTitleEdit: 'Edit Layer Properties',
  label_assigner_layerModal_layerName: 'Layer Name',
  label_assigner_layerModal_defaultScheme: 'Default Scheme',
  label_assigner_layerModal_attachedModifiers: 'Attached Modifiers',
  label_assigner_layerModal_exclusionGroup: 'Exclusion Group',
  label_assigner_layerModal_initialActive: 'Initial Active',
  hint_assigner_layerModal_layerName: 'Set layer name.',
  hint_assigner_layerModal_defaultScheme:
    'Set default behavior for keys. (transparent: skip this layer, block: stop lookup flow)',
  hint_assigner_layerModal_attachedModifiers:
    'Set attached modifiers activated together with the layer.',
  hint_assigner_layerModal_exclusionGroup:
    'Set layer exclusive group. Only at least one layer would activated at a time for layers within same group.',
  hint_assigner_layerModal_initialActive: 'Activate layer on startup.',
  label_assigner_newProfileModal_modalTitle: 'Create Profile',
  label_assigner_newProfileModal_profileName: 'Profile Name',
  label_assigner_newProfileModal_targetKeyboard: 'Target Keyboard',
  label_assigner_newProfileModal_layout: 'Layout',
  label_assigner_profileNameEditModal_modalTitleRename: 'Rename Profile',
  label_assigner_profileNameEditModal_modalTitleCopy: 'Save Profile As',
  label_assigner_profileNameEditModal_modalTitleSave: 'Save Profile',
  label_assigner_profileNameEditModal_newProfileName: 'New Profile Name',
  label_assigner_confirmModal_deleteProfile_modalTitle: 'Delete Profile',
  label_assigner_confirmModal_deleteProfile_modalMessage:
    'Profile {PROFILE_NAME} will be deleted. Are you sure?',
  label_assigner_confirmModal_loadProfile_modalTitle: 'Load Profile',
  label_assigner_confirmModal_loadProfile_modalMessage:
    'Unsaved changes will be lost. Are you ok?',
  label_presetBrowser_pageTitle: 'Preset Browser',
  label_presetBrowser2_pageTitle: 'User Preset Browser',
  label_presetBrowser_selectionTitle_keyboard: 'Keyboard',
  label_presetBrowser_selectionTitle_preset: 'Preset',
  label_presetBrowser_createProfileButton: 'Create Profile',
  label_presetBrowser_layers: 'Layers',
  hint_presetBrowser_selection_keyboard: 'Select keyboard model.',
  hint_presetBrowser_selection_preset: 'Select preset profile.',
  hint_presetBrowser_createProfileButton:
    'Create a new profile based on the selected preset.',
  hint_presetBrowser_projectLinkButton:
    'Select keyboard model corresponds to the connected device.',
  hint_presetBrowser_layers: 'Showing layers for selected preset.',
  label_device_deviceSelection_sectionTitle: 'Device Selection',
  hint_device_deviceSelection_selectionArea:
    'Supported devices are enumerated. Select device to connect.',
  label_device_deviceInfo_sectionTitle: 'Device Information',
  label_device_deviceInfo_fieldName_port: 'Port',
  label_device_deviceInfo_fieldName_resourceOrigin: 'Resource Origin',
  label_device_deviceInfo_fieldName_firmwareId: 'Firmware ID',
  label_device_deviceInfo_value_resourceOrigin_local: 'Local',
  label_device_deviceInfo_value_resourceOrigin_online: 'Online',
  label_device_deviceInfo_fieldName_projectPath: 'Project Path',
  label_device_deviceInfo_fieldName_keyboardName: 'Keyboard Name',
  label_device_deviceInfo_fieldName_instanceNumber: 'Instance Number',
  label_device_deviceInfo_fieldName_firmwareVariation:
    'Firmware Variation Name',
  label_device_deviceInfo_fieldName_mcuName: 'MCU Name',
  label_device_deviceInfo_fieldName_firmwareRevision: 'Firmware Revision',
  label_device_deviceInfo_fieldName_firmwareLatestRevision:
    'Firmware Latest Revision',
  label_device_deviceInfo_fieldName_firmwareLatestTimestamp:
    'Firmware Latest Build Timestamp',
  label_device_deviceInfo_fieldName_keymappingAreaSize: 'Keymapping Area Size',
  label_device_customParameters_sectionTitle: 'Custom Parameters',
  hint_device_customParameters_sectionArea:
    'Configure firmware specific parameters. ',
  label_device_customParameters_parametersUnavailable:
    'Parameter definitions are unavailable.',
  label_device_firmwareUpdate_sectionTitle: 'Firmware Update',
  label_device_firmwareUpdate_operationAlertText:
    'Note: Wrong firmware selection may damage the hardware. Be careful.',
  label_device_firmwareUpdate_projectSelector:
    'Select target keyboard project.',
  label_device_firmwareUpdate_usageText:
    'Double tap the reset button on the device.',
  label_device_firmwareUpdate_deviceDetected: '{DEVICE_NAME} detected.',
  label_device_firmwareUpdate_writeButton: 'write',
  label_device_firmwareUpdate_writing: 'Writing...',
  label_device_firmwareUpdate_success: 'Success!',
  label_device_firmwareUpdate_failure: 'Failure',
  label_device_firmwareUpdate_logButton: 'log',
  label_device_firmwareUpdate_doneButton: 'done',
  label_settings_pageTitle: 'Configurations',
  label_settings_header_resources: 'Resources',
  label_settings_configUseOnlineProjectResources:
    'Use Online Project Resources',
  label_settings_configUseLocalProjectResources: 'Use Local Repository Resources',
  label_settings_configKermiteRootDirectory: 'Kermite Root Directory',
  label_settings_header_userInterface: 'User Interface',
  label_settings_configUiScaling: 'UI Scaling',
  hint_settings_configUseOnlineProjectResources:
    'Use online resource. Access to KermiteResourceStore repository for the data.',
  hint_settings_configUseLocalProjectResources:
    'Use data resources on local machine.  Location of Kermite source code directory should be specified.',
  hint_settings_configKermiteRootDirectory:
    'Specify source code directory of Kermite. (for developers)',
  hint_settings_configUiScaling: 'Set scaling value for UI.',
  hint_statusBar_toggleHintMessageVisibility: 'Toggle visibility for UI hints.',
  label_projectAttachmentFileSelectionModal_savePreset_modalTitle:
    'Save As Project Preset',
  label_projectAttachmentFileSelectionModal_saveLayout_modalTitle:
    'Save As Project Layout',
  label_projectAttachmentFileSelectionModal_loadLayout_modalTitle:
    'Load From Project Layout',
  label_projectAttachmentFileSelectionModal_project: 'Project',
  label_projectAttachmentFileSelectionModal_preset: 'Preset',
  label_projectAttachmentFileSelectionModal_layout: 'Layout',
  label_sideMenu_app_assigner: 'Main',
  label_sideMenu_app_layoutEditor: 'Layouter',
  label_sideMenu_app_presetBrowser: 'Presets',
  label_sideMenu_app_shapePreview: 'Preview',
  label_sideMenu_app_firmwareUpdate: 'Device',
  label_sideMenu_app_settings: 'Settings',
  label_sideMenu_app_projectSelection: 'Keyboard',
  hint_sideMenu_app_assigner: 'Edit key assigns',
  hint_sideMenu_app_layoutEditor: 'Edit keyboard layout',
  hint_sideMenu_app_presetBrowser: 'View presets',
  hint_sideMenu_app_shapePreview: 'Preview keyboard shapes',
  hint_sideMenu_app_firmwareUpdate: 'Manage supported keyboard devices',
  hint_sideMenu_app_settings: 'Manage application settings',
};

// prettier-ignore
export const textSourceJapanese = {
  STUB: 'TODO: specify text for this element',
  hint_titleBar_switchToWidgetView: 'ウィジェット表示に切り替えます。',
  hint_titleBar_minimizeWindow: 'ウインドウを最小化します。',
  hint_titleBar_maximizeWindow: 'ウインドウを最大化します。',
  hint_titleBar_closeApplication: 'アプリケーションを終了します。',
  hint_globalMenuButton: 'グローバルメニューを表示します。',
  label_globalMenu_showTestInputArea: 'テスト入力欄を表示',
  label_globalMenu_theme_light: 'ライトテーマ',
  label_globalMenu_theme_dark: 'ダークテーマ',
  label_globalMenu_language_english: 'English',
  label_globalMenu_language_japanese: '日本語',
  hint_globalMenu_showTestInputArea: 'テスト入力欄を表示します。',
  hint_globalMenu_theme_light: 'ライトテーマに切り替えます。',
  hint_globalMenu_theme_dark: 'ダークテーマに切り替えます。',
  hint_globalMenu_language_english: 'UIを英語表示に切り替えます。',
  hint_globalMenu_language_japanese: 'UIを日本語表示に切り替えます。',
  hint_assigner_topBar_profileOperationsMenu:
    'プロファイル管理メニューを開きます。',
  label_assigner_menu_newProfile: '新規作成',
  label_assigner_menu_saveProfile: '名前をつけて保存',
  label_assigner_menu_renameProfile: '名前を変更',
  label_assigner_menu_copyProfile: '別名で保存',
  label_assigner_menu_deleteProfile: '削除',
  label_assigner_menu_importFromFile: '外部ファイルから読み込み',
  label_assigner_menu_exportToFile: '外部ファイルに保存',
  label_assigner_menu_saveAsPreset: 'プリセットとして保存',
  label_assigner_menu_openUserProfilesFolder: 'データの保存場所を開く',
  hint_assigner_menu_newProfile: '新規プロファイルを作成します。',
  hint_assigner_menu_saveProfile: 'プロファイルに名前をつけて保存します。',
  hint_assigner_menu_renameProfile: 'プロファイルの名前を変更します。',
  hint_assigner_menu_copyProfile: 'プロファイルを別名で保存します。',
  hint_assigner_menu_deleteProfile: 'プロファイルを削除します。',
  hint_assigner_menu_importFromFile:
    'ディスク上の任意にあるファイルからプロファイルを読み込みます。',
  hint_assigner_menu_exportToFile:
    'プロファイルをディスク上の任意の場所にファイルとして保存します。',
  hint_assigner_menu_saveAsPreset:
    'プロファイルをプロジェクトのプリセットとして保存します。',
  hint_assigner_menu_openUserProfilesFolder:
    'プロファイルの保存場所をOSのファイルマネージャで開きます。',
  label_assigner_topBar_saveAssignsButton: '保存',
  label_assigner_topBar_writeAssignsButton: '書き込み',
  hint_assigner_topBar_saveAssignsButton: '編集中のプロファイルを保存します',
  hint_assigner_topBar_writeAssignsButton:
    'プロファイルを保存して、デバイスにキーマッピングを書き込みます。',
  hint_assigner_topBar_selectCurrentProfile: 'プロファイルを選択します。',
  hint_assigner_topBar_profileConfigurationButton:
    'プロファイル設定ダイアログを開きます。',
  hint_assigner_topBar_keyboardBehaviorModeSelector:
    'キーボードの動作モードを設定します。(STD: スタンドアロン動作, SIM: シミュレーション動作)',
  hint_assigner_topBar_keyboardSystemLayoutSelector:
    'OSが認識するキーボードレイアウトを設定します',
  hint_assigner_topBar_routingChannelSelector:
    'アサインルーティングチャネルを選択します。',
  hint_assigner_topBar_connectedKeyboardName:
    '接続しているキーボードの品種名を表示しています。',
  hint_assigner_topBar_deviceConnectionStatus:
    'キーボードの接続状態を表示しています。',
  label_assigner_testInputArea_clearButton: 'クリア',
  hint_assigner_testInputArea_inputField:
    'キーボードの動作確認用の入力欄です。',
  hint_assigner_testInputArea_clearButton: '入力欄をクリアします。',
  hint_assigner_keyboardView_layerStates:
    'デバイスの現在のレイヤ状態を表示しています。',
  hint_assigner_keyboardView_keyUnit: 'アサイン設定対象のキーを選択します',
  hint_assigner_assigns_pri:
    'プライマリアサインスロットを選択します。キーを押下またはタップしたときに適用されます。',
  hint_assigner_assigns_sec:
    'セカンダリアサインスロットを選択します。キーを押下またはタップしたときに適用されます。',
  hint_assigner_assigns_ter:
    'ターシャリアサインスロットを割り当てます。キーを素早く2回タップしたときに適用されます。',
  hint_assigner_assigns_none: 'アサインを解除します。',
  hint_assigner_assigns_transparent:
    '透過アサインを割り当てます。アサイン探索処理が次のレイヤに引き継がれます。',
  hint_assigner_assigns_block:
    'ブロックアサインを割り当てます。アサイン探索処理がこのレイヤで終了します。',
  hint_assigner_assigns_keyInput: 'キー入力を割り当てます。',
  hint_assigner_assigns_modifiers:
    'キー入力に対して適用されるモディファイヤキーを割り当てます。',
  hint_assigner_assigns_layers: 'レイヤ呼び出しを割り当てます。',
  hint_assigner_assigns_clearExclusiveGroup:
    '排他レイヤグループに対して、グループに所属する全レイヤを解除します。',
  hint_assigner_assigns_layerInvocationModeSelector:
    'レイヤ呼び出しモードを選択します。',
  label_assigner_layerListHeader: 'レイヤ',
  hint_assigner_layers_layerListHeader:
    'プロファイルが持っているレイヤのリストです。',
  hint_assigner_layers_layerListItems: '編集対象のレイヤを選択します。',
  hint_assigner_layerOps_addNewLayer: '新規レイヤを追加します。',
  hint_assigner_layerOps_editLayerProperties: 'レイヤの設定を編集します。',
  hint_assigner_layerOps_deleteLayer: 'レイヤを削除します。',
  hint_assigner_layerOps_bringBackward: 'レイヤを後ろに移動します。',
  hint_assigner_layerOps_bringForward: 'レイヤを前に移動します。',
  label_assigner_configs_assignModel: 'ロジックモデル',
  label_assigner_configs_showLayersDynamic: 'デバイスのレイヤを反映',
  label_assigner_configs_showFallbackAssigns: 'デフォルトアサインを表示',
  hint_assigner_configs_assignModel:
    'プロファイルのアサインモデルを表示しています。',
  hint_assigner_configs_showLayersDynamic:
    'デバイスのレイヤ状態に同期して表示するレイヤを切り替えます。',
  hint_assigner_configs_showFallbackAssigns:
    'レイヤのデフォルトアサインを表示します。',
  label_assigner_profileConfigModal_modalTitle: 'プロファイル設定',
  label_assigner_profileConfigModal_assignModel: 'ロジックモデル',
  label_assigner_profileConfigModal_dualMode_header: 'Dualモード設定',
  label_assigner_profileConfigModal_dualMode_primaryDefaultTrigger:
    'デフォルトトリガ',
  label_assigner_profileConfigModal_dualMode_tapHoldThreshold: 'タップ判定時間',
  label_assigner_profileConfigModal_dualMode_useInterruptHold:
    '割り込みホールド機能を使用',
  label_assigner_profileConfigModal_shiftCancel: 'Shiftキャンセル機能を使用',
  hint_assigner_profileConfigModal_assignModel:
    'ロジックモデルを選択します。(single: キーに対して単一の機能を割り当てるモデル, dual: キー毎にタップ/ホールドによって切り替わる複数の機能を割り当てるモデル)',
  hint_assigner_profileConfigModal_dualMode_header:
    'ロジックモデル:dual に固有の設定です',
  hint_assigner_profileConfigModal_dualMode_primaryDefaultTrigger:
    'セカンダリアサインがない場合のプライマリアサインの実行トリガを指定します。(down: 押下時に適用, tap: タップで適用)',
  hint_assigner_profileConfigModal_dualMode_tapHoldThreshold:
    'キーを押し続けたときにホールドしたとみなされる時間を指定します。',
  hint_assigner_profileConfigModal_dualMode_useInterruptHold:
    'ホールド時間に満たないときに割り込んで他のキーが押された場合に、1つ目のキーをホールド状態に移行します。',
  hint_assigner_profileConfigModal_shiftCancel:
    'shiftを押しながら本来shiftなしで入力される記号を入力したい場合に、shiftを一時的にキャンセル状態にします。',
  label_assigner_layerModal_modalTitleAdd: 'レイヤを追加',
  label_assigner_layerModal_modalTitleEdit: 'レイヤプロパティ',
  label_assigner_layerModal_layerName: 'レイヤ名',
  label_assigner_layerModal_defaultScheme: 'デフォルトスキーム',
  label_assigner_layerModal_attachedModifiers: '添付モディファイヤ',
  label_assigner_layerModal_exclusionGroup: 'レイヤ排他グループ',
  label_assigner_layerModal_initialActive: '初期状態でレイヤを有効化',
  hint_assigner_layerModal_layerName: 'レイヤの名前を設定します。',
  hint_assigner_layerModal_defaultScheme:
    'キーのデフォルトの挙動を設定します(transparent: スキップして次のレイヤに進む, block: 探索終了)',
  hint_assigner_layerModal_attachedModifiers:
    'レイヤを有効化したときに同時に有効になるモディファイヤキーを設定します。',
  hint_assigner_layerModal_exclusionGroup:
    'レイヤ排他グループを設定します。同じグループに所属するレイヤのうち、1つのみが有効になります。',
  hint_assigner_layerModal_initialActive:
    'キーボードの起動時に、レイヤが始めから有効化された状態にします。',
  label_assigner_newProfileModal_modalTitle: 'プロファイルを作成',
  label_assigner_newProfileModal_profileName: 'プロファイル名',
  label_assigner_newProfileModal_targetKeyboard: 'キーボード',
  label_assigner_newProfileModal_layout: 'レイアウト',
  label_assigner_profileNameEditModal_modalTitleRename:
    'プロファイルの名前を変更',
  label_assigner_profileNameEditModal_modalTitleCopy: 'プロファイルを別名で保存',
  label_assigner_profileNameEditModal_modalTitleSave: 'プロファイルを保存',
  label_assigner_profileNameEditModal_newProfileName: 'プロファイル名',
  label_assigner_confirmModal_deleteProfile_modalTitle: 'プロファイルを削除',
  label_assigner_confirmModal_deleteProfile_modalMessage:
    'プロファイル {PROFILE_NAME} が削除されます。よろしいですか?',
  label_assigner_confirmModal_loadProfile_modalTitle: 'プロファイルを読み込み',
  label_assigner_confirmModal_loadProfile_modalMessage:
    '保存されていない変更は破棄されます。よろしいですか。',
  label_presetBrowser_pageTitle: 'プリセットブラウザ',
  label_presetBrowser2_pageTitle: 'ユーザープリセットブラウザ',
  label_presetBrowser_selectionTitle_keyboard: 'キーボード',
  label_presetBrowser_selectionTitle_preset: 'プリセット',
  label_presetBrowser_createProfileButton: 'プロファイルを作成',
  label_presetBrowser_layers: 'レイヤ',
  hint_presetBrowser_selection_keyboard: 'キーボードの品種を選択します。',
  hint_presetBrowser_selection_preset: 'プリセットを選択します。',
  hint_presetBrowser_createProfileButton:
    '選択されたプリセットから新しいプロファイルを作成します。',
  hint_presetBrowser_projectLinkButton:
    '接続されているデバイスに紐付くキーボード品種を選択します。',
  hint_presetBrowser_layers:
    '選択されたプリセットのレイヤリストを表示しています。',
  label_device_deviceSelection_sectionTitle: 'デバイス選択',
  hint_device_deviceSelection_selectionArea:
    '対応しているデバイスが列挙されます。接続するデバイスを選択します。',
  label_device_deviceInfo_sectionTitle: 'デバイス情報',
  label_device_deviceInfo_fieldName_port: 'ポート',
  label_device_deviceInfo_fieldName_resourceOrigin: 'リソースオリジン',
  label_device_deviceInfo_fieldName_firmwareId: 'ファームウェアID',
  label_device_deviceInfo_value_resourceOrigin_local: 'ローカル',
  label_device_deviceInfo_value_resourceOrigin_online: 'オンライン',
  label_device_deviceInfo_fieldName_projectPath: 'プロジェクトパス',
  label_device_deviceInfo_fieldName_keyboardName: 'キーボード名',
  label_device_deviceInfo_fieldName_instanceNumber: '個体番号',
  label_device_deviceInfo_fieldName_firmwareVariation:
    'ファームウェアバリエーション',
  label_device_deviceInfo_fieldName_mcuName: 'MCU品種名',
  label_device_deviceInfo_fieldName_firmwareRevision:
    'ファームウェアリビジョン',
  label_device_deviceInfo_fieldName_firmwareLatestRevision:
    'ファームウェア最新リビジョン',
  label_device_deviceInfo_fieldName_firmwareLatestTimestamp:
    'ファームウェア最新ビルド日時',
  label_device_deviceInfo_fieldName_keymappingAreaSize:
    'キーマッピング領域サイズ',
  label_device_customParameters_sectionTitle: 'カスタムパラメータ',
  hint_device_customParameters_sectionArea:
    'ファームウェア固有のパラメータを設定します。',
  label_device_customParameters_parametersUnavailable:
    'パラメータの定義が利用できません。',
  label_device_firmwareUpdate_sectionTitle: 'ファームウェア書き込み',
  label_device_firmwareUpdate_operationAlertText:
    '誤ったファームウェアを書き込むとデバイスが破損する可能性があります。ご注意ください。',
  label_device_firmwareUpdate_projectSelector:
    'デバイスに書き込むファームウェアを選択します。',
  label_device_firmwareUpdate_usageText:
    'デバイスのリセットボタンを2回タップして、ファームウェア書き込みモードにしてください。',
  label_device_firmwareUpdate_deviceDetected:
    '{DEVICE_NAME}に対応デバイスを認識しました。',
  label_device_firmwareUpdate_writeButton: '書き込む',
  label_device_firmwareUpdate_writing: '書き込んでいます...',
  label_device_firmwareUpdate_success: '成功しました!',
  label_device_firmwareUpdate_failure: '書き込みに失敗しました。',
  label_device_firmwareUpdate_logButton: 'ログ',
  label_device_firmwareUpdate_doneButton: '完了',
  label_settings_pageTitle: '設定',
  label_settings_header_resources: 'リソース',
  label_settings_configUseOnlineProjectResources:
    'オンラインプロジェクトリソースを使用',
  label_settings_configUseLocalProjectResources:
    'ローカルリポジトリ内のリソースを参照',
  label_settings_configKermiteRootDirectory: 'Kermiteのソースコードの場所',
  label_settings_header_userInterface: 'ユーザーインターフェイス',
  label_settings_configUiScaling: 'UIスケーリング',
  hint_settings_configUseOnlineProjectResources:
    'オンラインリソースを使用します。KermiteResourceStoreリポジトリに配置してあるデータを参照します。',
  hint_settings_configUseLocalProjectResources:
    'ローカルマシンにあるリソースを使用します。Kermiteのソースコードの場所の指定が必要です。',
  hint_settings_configKermiteRootDirectory:
    'Kermiteのソースコードのルートフォルダを指定します (ファームウェア開発者向け)',
  hint_settings_configUiScaling:
    '画面のスケーリング値を設定します。文字の大きさが変わります。',
  hint_statusBar_toggleHintMessageVisibility:
    'ヒントの表示/非表示を切り替えます。',
  label_projectAttachmentFileSelectionModal_savePreset_modalTitle:
    'プロジェクトのプリセットとして保存',
  label_projectAttachmentFileSelectionModal_saveLayout_modalTitle:
    'プロジェクトのレイアウトとして保存',
  label_projectAttachmentFileSelectionModal_loadLayout_modalTitle:
    'プロジェクトのレイアウトを読み込み',
  label_projectAttachmentFileSelectionModal_project: 'プロジェクト',
  label_projectAttachmentFileSelectionModal_preset: 'プリセット',
  label_projectAttachmentFileSelectionModal_layout: 'レイアウト',
  label_sideMenu_app_assigner: 'メイン',
  label_sideMenu_app_layoutEditor: 'レイアウト',
  label_sideMenu_app_presetBrowser: 'プリセット',
  label_sideMenu_app_shapePreview: 'プレビュー',
  label_sideMenu_app_firmwareUpdate: 'デバイス',
  label_sideMenu_app_settings: '設定',
  label_sideMenu_app_projectSelection: 'キーボード',
  hint_sideMenu_app_assigner: 'キーアサインを編集します。',
  hint_sideMenu_app_layoutEditor: 'キーの配置を編集します。',
  hint_sideMenu_app_presetBrowser: 'プリセットを閲覧します。',
  hint_sideMenu_app_shapePreview: 'キーボードの形状を表示します。',
  hint_sideMenu_app_firmwareUpdate: 'デバイスの管理を行います。',
  hint_sideMenu_app_settings: 'アプリの設定を行います。',
};
