#ifndef __CONFIG_H__

#define KERMITE_PROJECT_ID "00000000"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 0

#define KM0_ATMEGA_SINGLEWIRE__PIN_SIGNAL_PD0

#define KM0_RGB_LIGHTING__NUM_LEDS 0

#define KM0_ATMEGA_NEOPIXELCORE__PIN_RGBLED P_F4

#define KS_NUM_COLUMNS 0
#define KS_NUM_ROWS 0

#define KS_COLUMN_PINS \
  {}

#define KS_ROW_PINS \
  {}

#endif