#ifndef __CONFIG_H__

#define KERMITE_PROJECT_ID "ABC12345"

#define KM0_KEYBOARD__NUM_SCAN_SLOTS 40
#define KM0_KEYBOARD__NUM_KEY_SLOTS 40

#define KM0_ATMEGA_SINGLEWIRE__PIN_SIGNAL_PD0

#define KM0_RGB_LIGHTING__NUM_LEDS 40

#define KM0_ATMEGA_NEOPIXELCORE__PIN_RGBLED P_F4

#endif