name: Firmware ErrorCheck

on:
  push:
    branches: [variants-dev]
    paths:
      - ".github/workflows/firmware_error_check.yml"
      - "firmware/ci/**/*.ts"
      - "firmware/Makefile"
      - "firmware/workers/*.mk"
      - "firmware/src/**"
      - "software/src/shell/loaders/**/*.ts"

  pull_request:
    branches: [variants]
    types: [opened, synchronize]
    paths:
      - "firmware/Makefile"
      - "firmware/workers/*.mk"
      - "firmware/src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: install avr-gcc
        run: |
          mkdir -p ~/tools
          wget https://app.kermite.org/toolset/avr-gcc-11.1.0-x64-linux.tar.bz2
          tar -C ~/tools -xf avr-gcc-11.1.0-x64-linux.tar.bz2
          echo `echo ~/tools/avr-gcc-11.1.0-x64-linux/bin` >> $GITHUB_PATH

      - name: install arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: "10-2020-q4"

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ./firmware/ci

      - run: yarn checkHardcodedVersions
        working-directory: ./firmware/ci

      - name: Check Firmware IDs
        run: yarn checkFirmwareIds
        working-directory: ./firmware/ci

      - name: Check Firmware Build Errors
        run: yarn buildUpdatedProjects
        working-directory: ./firmware/ci
