#pragma once

#define KERMITE_FIRMWARE_ID "Z9G7dk"
#define KERMITE_KEYBOARD_NAME "keydrip7"

#define KS_NUM_SCAN_SLOTS 7

#define KS_NUM_DIRECT_WIRED_KEYS 7

#define KS_DIRECT_WIRED_KEY_INPUT_PINS \
  { GP3, GP28, GP27, GP26, GP29, GP6, GP7 }
